server {
    listen 80;
    server_name php.starfleet.lan;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name php.starfleet.lan;

    ssl_certificate     /etc/ssl/starfleet/starfleet.lan.crt;
    ssl_certificate_key /etc/ssl/starfleet/starfleet.lan.key;

    root /var/www/phpmyadmin;
    index index.php index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include /etc/nginx/fastcgi_params;
        fastcgi_pass unix:/run/php/php8.4-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
