server {
    listen 80;
    server_name www8.starfleet.lan;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name www8.starfleet.lan;

    ssl_certificate     /etc/ssl/starfleet/starfleet.lan.crt;
    ssl_certificate_key /etc/ssl/starfleet/starfleet.lan.key;

    root /var/www/www8;
    index index.php index.html;

    location = /auth-proxy {
        internal;
        proxy_pass http://127.0.0.1:8888;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Ldap-URL "ldap://127.0.0.1:389";
        proxy_set_header X-Ldap-BaseDN "ou=people,dc=starfleet,dc=lan";
        proxy_set_header X-Ldap-BindDN "cn=admin,dc=starfleet,dc=lan";
        proxy_set_header X-Ldap-BindPass "VOTRE_MOT_DE_PASSE_LDAP";
    }

    location /prive/ {
        auth_request /auth-proxy;
        auth_request_set $ldap_user $upstream_http_x_username;
        try_files $uri $uri/ /prive/index.php;

        location ~ \.php$ {
            include /etc/nginx/fastcgi_params;
            fastcgi_pass unix:/run/php/php8.4-fpm.sock;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param HTTP_AUTHORIZATION $http_authorization;
        }
    }

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include /etc/nginx/fastcgi_params;
        fastcgi_pass unix:/run/php/php8.4-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
